# Generated by Django 4.2 on 2024-08-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(default='beze jména', max_length=50)),
                ('datum', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('popis', models.TextField(max_length=5000)),
            ],
        ),
    ]
