# Generated by Django 4.2 on 2024-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_holubu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holubi',
            options={'verbose_name_plural': 'Holubi'},
        ),
        migrations.AlterField(
            model_name='holubi',
            name='adresa',
            field=models.CharField(blank=True, help_text='Adresa bude automaticky vyplněna na základě GPS souřadnic.', max_length=255),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='datum',
            field=models.DateField(blank=True, help_text='Vyberte datum události (nepovinný udaj).', null=True),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='jmeno',
            field=models.CharField(default='beze jména', help_text='Zadejte jméno holuba. Pokud neznáte jméno, ponechte výchozí hodnotu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Zadejte zeměpisnou šířku - latitude (maximálně 10 číslic). Souřadnice zjistíte zde: https://www.geocords.com/address-to-lat-long/', max_digits=10),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Zadejte zeměpisnou délku - longitude (maximálně 10 číslic). Souřadnice zjistíte zde: https://www.geocords.com/address-to-lat-long/', max_digits=10),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='popis',
            field=models.TextField(help_text='Zadejte popis (maximálně 5 000 znaků).', max_length=5000),
        ),
    ]
