# Generated by Django 4.2 on 2024-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_holubu', '0002_alter_holubi_options_alter_holubi_adresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holubi',
            name='adresa',
            field=models.CharField(help_text='Zadejte adresu události (lze zkopírovat z odkazu se souřadnicemi).', max_length=255),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text="Zadejte zeměpisnou šířku - latitude (maximálně 10 číslic). Souřadnice můžete zjistit pomocí tohoto odkazu: <a href='https://www.geocords.com/address-to-lat-long/' target='_blank'>Získat souřadnice</a>.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text="Zadejte zeměpisnou délku - longitude (maximálně 10 číslic). Souřadnice můžete zjistit pomocí tohoto odkazu: <a href='https://www.geocords.com/address-to-lat-long/' target='_blank'>Získat souřadnice</a>.", max_digits=10),
        ),
    ]
