# Generated by Django 4.2 on 2024-09-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_holubu', '0003_alter_holubi_adresa_alter_holubi_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holubi',
            name='potvrzena_streba',
            field=models.BooleanField(default=False, help_text='Zaškrtněte, pokud je střeba potvrzena.'),
        ),
        migrations.AddField(
            model_name='holubi',
            name='prezil',
            field=models.BooleanField(default=True, help_text='Zaškrtněte, pokud holoubek událost přežil.'),
        ),
        migrations.AlterField(
            model_name='holubi',
            name='jmeno',
            field=models.CharField(default='beze jména', help_text='Zadejte jméno holoubka. Pokud jméno nemá, ponechte výchozí hodnotu.', max_length=50),
        ),
        migrations.CreateModel(
            name='ImgHolubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='holubi_img/')),
                ('description', models.CharField(blank=True, help_text='Zadejte popis obrázku (nepovinné).', max_length=255)),
                ('holub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mapa_holubu.holubi')),
            ],
        ),
    ]
